package com.csi.modules.qzdy.dao;

import com.csi.modules.qzdy.entity.QZDYEntity;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.Param;
import java.util.List;

/**
 * 
 * 
 * @author linmengmeng
 * @email 1632284989@qq.com
 * @date 2020-07-28 11:25:56
 */
@Mapper
public interface QZDYDao {

	@Select({
			"<script>",
			"SELECT * FROM ",  
			"(  ",
			"SELECT A.* ", 
			"FROM (",
			"select",
			        "ROWNUM RN, ",
					"DWDM, ",
					"XH, ",
					"CXD, ",
					"QZZL, ",
					"ZHXGR, ",
					"QH, ",
					"ZHXGSJ, ",
					"LRSJ, ",
					"SCRQ, ",
					"LRIP, ",
					"QZXH, ",
					"LRR, ",
					"ZHXGIP, ",
					"ZT, ",
					"QZZT, ",
					"GMRQ, ",
					"SCCJ",
			"from",
				"(T_DW_MQJBXX_QZCL_MX) F",
			"<where>",
				"<if test='entity.dwdm != null and entity.dwdm != \"\" '>AND DWDM = #{entity.dwdm} </if>",
				"<if test='entity.xh != null '>and XH = #{entity.xh} </if>",
				"<if test='entity.cxd != null and entity.cxd != \"\" '>AND CXD = #{entity.cxd} </if>",
				"<if test='entity.qzzl != null and entity.qzzl != \"\" '>AND QZZL = #{entity.qzzl} </if>",
				"<if test='entity.zhxgr != null and entity.zhxgr != \"\" '>AND ZHXGR = #{entity.zhxgr} </if>",
				"<if test='entity.qh != null and entity.qh != \"\" '>AND QH = #{entity.qh} </if>",
				"<if test='entity.zhxgsj != null '>and ZHXGSJ = #{entity.zhxgsj} </if>",
				"<if test='entity.lrsj != null '>and LRSJ = #{entity.lrsj} </if>",
				"<if test='entity.scrq != null '>and SCRQ = #{entity.scrq} </if>",
				"<if test='entity.lrip != null and entity.lrip != \"\" '>AND LRIP = #{entity.lrip} </if>",
				"<if test='entity.qzxh != null and entity.qzxh != \"\" '>AND QZXH = #{entity.qzxh} </if>",
				"<if test='entity.lrr != null and entity.lrr != \"\" '>AND LRR = #{entity.lrr} </if>",
				"<if test='entity.zhxgip != null and entity.zhxgip != \"\" '>AND ZHXGIP = #{entity.zhxgip} </if>",
				"<if test='entity.zt != null and entity.zt != \"\" '>AND ZT = #{entity.zt} </if>",
				"<if test='entity.qzzt != null and entity.qzzt != \"\" '>AND QZZT = #{entity.qzzt} </if>",
				"<if test='entity.gmrq != null '>and GMRQ = #{entity.gmrq} </if>",
				"<if test='entity.sccj != null and entity.sccj != \"\" '>AND SCCJ = #{entity.sccj}</if>",
			"</where>",
			") A ",
			"WHERE <![CDATA[ ROWNUM < #{endRow}  ]]>",
			") B",
			"WHERE <![CDATA[ RN > #{startRow} ]]>",
			"</script>"
    })
	List<QZDYEntity> selectEntityListForPage(@Param("entity")QZDYEntity qZDYEntity,@Param("startRow")Long startRow,@Param("endRow")Long endRow);
	
	@Select({
			"<script>",
			"select",
			        "count(1) ",
			"from",
				"(T_DW_MQJBXX_QZCL_MX) F",
			"<where>",
				"<if test='entity.dwdm != null and entity.dwdm != \"\" '>AND DWDM = #{entity.dwdm} </if>",
				"<if test='entity.xh != null '>and XH = #{entity.xh} </if>",
				"<if test='entity.cxd != null and entity.cxd != \"\" '>AND CXD = #{entity.cxd} </if>",
				"<if test='entity.qzzl != null and entity.qzzl != \"\" '>AND QZZL = #{entity.qzzl} </if>",
				"<if test='entity.zhxgr != null and entity.zhxgr != \"\" '>AND ZHXGR = #{entity.zhxgr} </if>",
				"<if test='entity.qh != null and entity.qh != \"\" '>AND QH = #{entity.qh} </if>",
				"<if test='entity.zhxgsj != null '>and ZHXGSJ = #{entity.zhxgsj} </if>",
				"<if test='entity.lrsj != null '>and LRSJ = #{entity.lrsj} </if>",
				"<if test='entity.scrq != null '>and SCRQ = #{entity.scrq} </if>",
				"<if test='entity.lrip != null and entity.lrip != \"\" '>AND LRIP = #{entity.lrip} </if>",
				"<if test='entity.qzxh != null and entity.qzxh != \"\" '>AND QZXH = #{entity.qzxh} </if>",
				"<if test='entity.lrr != null and entity.lrr != \"\" '>AND LRR = #{entity.lrr} </if>",
				"<if test='entity.zhxgip != null and entity.zhxgip != \"\" '>AND ZHXGIP = #{entity.zhxgip} </if>",
				"<if test='entity.zt != null and entity.zt != \"\" '>AND ZT = #{entity.zt} </if>",
				"<if test='entity.qzzt != null and entity.qzzt != \"\" '>AND QZZT = #{entity.qzzt} </if>",
				"<if test='entity.gmrq != null '>and GMRQ = #{entity.gmrq} </if>",
				"<if test='entity.sccj != null and entity.sccj != \"\" '>AND SCCJ = #{entity.sccj}</if>",
			"</where>",
			"</script>"
    })
	Long selectEntityListForPageCount(@Param("entity")QZDYEntity qZDYEntity);
	
	@Select({
			"<script>",
			"select",
					"DWDM, ",
					"XH, ",
					"CXD, ",
					"QZZL, ",
					"ZHXGR, ",
					"QH, ",
					"ZHXGSJ, ",
					"LRSJ, ",
					"SCRQ, ",
					"LRIP, ",
					"QZXH, ",
					"LRR, ",
					"ZHXGIP, ",
					"ZT, ",
					"QZZT, ",
					"GMRQ, ",
					"SCCJ",
			"from",
				"T_DW_MQJBXX_QZCL_MX",
			"<where>",
				"<if test='dwdm != null and dwdm != \"\" '>AND DWDM = #{dwdm} </if>",
				"<if test='xh != null '>and XH = #{xh} </if>",
				"<if test='cxd != null and cxd != \"\" '>AND CXD = #{cxd} </if>",
				"<if test='qzzl != null and qzzl != \"\" '>AND QZZL = #{qzzl} </if>",
				"<if test='zhxgr != null and zhxgr != \"\" '>AND ZHXGR = #{zhxgr} </if>",
				"<if test='qh != null and qh != \"\" '>AND QH = #{qh} </if>",
				"<if test='zhxgsj != null '>and ZHXGSJ = #{zhxgsj} </if>",
				"<if test='lrsj != null '>and LRSJ = #{lrsj} </if>",
				"<if test='scrq != null '>and SCRQ = #{scrq} </if>",
				"<if test='lrip != null and lrip != \"\" '>AND LRIP = #{lrip} </if>",
				"<if test='qzxh != null and qzxh != \"\" '>AND QZXH = #{qzxh} </if>",
				"<if test='lrr != null and lrr != \"\" '>AND LRR = #{lrr} </if>",
				"<if test='zhxgip != null and zhxgip != \"\" '>AND ZHXGIP = #{zhxgip} </if>",
				"<if test='zt != null and zt != \"\" '>AND ZT = #{zt} </if>",
				"<if test='qzzt != null and qzzt != \"\" '>AND QZZT = #{qzzt} </if>",
				"<if test='gmrq != null '>and GMRQ = #{gmrq} </if>",
				"<if test='sccj != null and sccj != \"\" '>AND SCCJ = #{sccj}</if>",
			"</where>",
			"</script>"
    })
	List<QZDYEntity> selectEntityListAll(QZDYEntity qZDYEntity);

	@Select({
			"<script>",
			"select",
					"SEQ_T_DW_MQJBXX_QZCL_MX.nextval",
			"from",
				"dual",
			"</script>"
    })
	Long selectSequenceId();

	@Insert({
			"insert into T_DW_MQJBXX_QZCL_MX",
				"(",
					"DWDM, ",
					"XH, ",
					"CXD, ",
					"QZZL, ",
					"ZHXGR, ",
					"QH, ",
					"ZHXGSJ, ",
					"LRSJ, ",
					"SCRQ, ",
					"LRIP, ",
					"QZXH, ",
					"LRR, ",
					"ZHXGIP, ",
					"ZT, ",
					"QZZT, ",
					"GMRQ, ",
					"SCCJ",
				")",
			"values",
				"(",
					"#{dwdm,jdbcType=VARCHAR}, ",
					"#{xh,jdbcType=BIGINT}, ",
					"#{cxd,jdbcType=VARCHAR}, ",
					"#{qzzl,jdbcType=VARCHAR}, ",
					"#{zhxgr,jdbcType=VARCHAR}, ",
					"#{qh,jdbcType=VARCHAR}, ",
					"#{zhxgsj,jdbcType=DATE}, ",
					"#{lrsj,jdbcType=DATE}, ",
					"#{scrq,jdbcType=DATE}, ",
					"#{lrip,jdbcType=VARCHAR}, ",
					"#{qzxh,jdbcType=VARCHAR}, ",
					"#{lrr,jdbcType=VARCHAR}, ",
					"#{zhxgip,jdbcType=VARCHAR}, ",
					"#{zt,jdbcType=VARCHAR}, ",
					"#{qzzt,jdbcType=VARCHAR}, ",
					"#{gmrq,jdbcType=DATE}, ",
					"#{sccj,jdbcType=VARCHAR}",
				")"
    })
	int insertEntity(QZDYEntity qZDYEntity);
	
	@Insert({
			"<script>",
			"insert into T_DW_MQJBXX_QZCL_MX",
				"(",
				"DWDM, ",
				"XH, ",
				"CXD, ",
				"QZZL, ",
				"ZHXGR, ",
				"QH, ",
				"ZHXGSJ, ",
				"LRSJ, ",
				"SCRQ, ",
				"LRIP, ",
				"QZXH, ",
				"LRR, ",
				"ZHXGIP, ",
				"ZT, ",
				"QZZT, ",
				"GMRQ, ",
				"SCCJ",
				")",
			"values",
			"<foreach collection ='list' item='obj' separator =','>",
				"(",
					"#{obj.dwdm,jdbcType=VARCHAR}, ",
					"#{obj.xh,jdbcType=BIGINT}, ",
					"#{obj.cxd,jdbcType=VARCHAR}, ",
					"#{obj.qzzl,jdbcType=VARCHAR}, ",
					"#{obj.zhxgr,jdbcType=VARCHAR}, ",
					"#{obj.qh,jdbcType=VARCHAR}, ",
					"#{obj.zhxgsj,jdbcType=DATE}, ",
					"#{obj.lrsj,jdbcType=DATE}, ",
					"#{obj.scrq,jdbcType=DATE}, ",
					"#{obj.lrip,jdbcType=VARCHAR}, ",
					"#{obj.qzxh,jdbcType=VARCHAR}, ",
					"#{obj.lrr,jdbcType=VARCHAR}, ",
					"#{obj.zhxgip,jdbcType=VARCHAR}, ",
					"#{obj.zt,jdbcType=VARCHAR}, ",
					"#{obj.qzzt,jdbcType=VARCHAR}, ",
					"#{obj.gmrq,jdbcType=DATE}, ",
					"#{obj.sccj,jdbcType=VARCHAR}",
				")",
			"</foreach >",
			"</script>",
    })
	int batchInsertEntity(@Param("list")List<QZDYEntity> qZDYEntitys);
	
	@Update({
			"<script>",
			"update T_DW_MQJBXX_QZCL_MX",
				"<set>",
					"<if test='entity.xh != null'>XH = #{entity.xh}, </if>",
					"<if test='entity.cxd != null'>CXD = #{entity.cxd}, </if>",
					"<if test='entity.qzzl != null'>QZZL = #{entity.qzzl}, </if>",
					"<if test='entity.zhxgr != null'>ZHXGR = #{entity.zhxgr}, </if>",
					"<if test='entity.qh != null'>QH = #{entity.qh}, </if>",
					"<if test='entity.zhxgsj != null'>ZHXGSJ = #{entity.zhxgsj}, </if>",
					"<if test='entity.lrsj != null'>LRSJ = #{entity.lrsj}, </if>",
					"<if test='entity.scrq != null'>SCRQ = #{entity.scrq}, </if>",
					"<if test='entity.lrip != null'>LRIP = #{entity.lrip}, </if>",
					"<if test='entity.qzxh != null'>QZXH = #{entity.qzxh}, </if>",
					"<if test='entity.lrr != null'>LRR = #{entity.lrr}, </if>",
					"<if test='entity.zhxgip != null'>ZHXGIP = #{entity.zhxgip}, </if>",
					"<if test='entity.zt != null'>ZT = #{entity.zt}, </if>",
					"<if test='entity.qzzt != null'>QZZT = #{entity.qzzt}, </if>",
					"<if test='entity.gmrq != null'>GMRQ = #{entity.gmrq}, </if>",
					"<if test='entity.sccj != null'>SCCJ = #{entity.sccj}</if>",
				"</set>",
				"where DWDM = #{entity.dwdm}",
			"</script>"
	})
	int updateEntity(@Param("entity")QZDYEntity qZDYEntity);

	@Update({
			"<script>",
			"<foreach collection ='list' item='obj' separator =';'>",
				"update T_DW_MQJBXX_QZCL_MX",
					"<set>",
						"<if test='list.xh != null'>XH = #{obj.xh}, </if>",
						"<if test='list.cxd != null'>CXD = #{obj.cxd}, </if>",
						"<if test='list.qzzl != null'>QZZL = #{obj.qzzl}, </if>",
						"<if test='list.zhxgr != null'>ZHXGR = #{obj.zhxgr}, </if>",
						"<if test='list.qh != null'>QH = #{obj.qh}, </if>",
						"<if test='list.zhxgsj != null'>ZHXGSJ = #{obj.zhxgsj}, </if>",
						"<if test='list.lrsj != null'>LRSJ = #{obj.lrsj}, </if>",
						"<if test='list.scrq != null'>SCRQ = #{obj.scrq}, </if>",
						"<if test='list.lrip != null'>LRIP = #{obj.lrip}, </if>",
						"<if test='list.qzxh != null'>QZXH = #{obj.qzxh}, </if>",
						"<if test='list.lrr != null'>LRR = #{obj.lrr}, </if>",
						"<if test='list.zhxgip != null'>ZHXGIP = #{obj.zhxgip}, </if>",
						"<if test='list.zt != null'>ZT = #{obj.zt}, </if>",
						"<if test='list.qzzt != null'>QZZT = #{obj.qzzt}, </if>",
						"<if test='list.gmrq != null'>GMRQ = #{obj.gmrq}, </if>",
						"<if test='list.sccj != null'>SCCJ = #{obj.sccj}</if>",
					"</set>",
					"where DWDM = #{entity.dwdm}",
			"</foreach >",
			"</script>"
	})
	int batchUpdateEntity(@Param("list")List<QZDYEntity> qZDYEntitys);
	
	@Delete({
			"<script>",
				"delete from T_DW_MQJBXX_QZCL_MX",
				"<where>",
					"<if test='entity.dwdm != null'>DWDM = #{dwdm} </if>",
					"<if test='entity.xh != null'>XH = #{xh} </if>",
					"<if test='entity.cxd != null'>CXD = #{cxd} </if>",
					"<if test='entity.qzzl != null'>QZZL = #{qzzl} </if>",
					"<if test='entity.zhxgr != null'>ZHXGR = #{zhxgr} </if>",
					"<if test='entity.qh != null'>QH = #{qh} </if>",
					"<if test='entity.zhxgsj != null'>ZHXGSJ = #{zhxgsj} </if>",
					"<if test='entity.lrsj != null'>LRSJ = #{lrsj} </if>",
					"<if test='entity.scrq != null'>SCRQ = #{scrq} </if>",
					"<if test='entity.lrip != null'>LRIP = #{lrip} </if>",
					"<if test='entity.qzxh != null'>QZXH = #{qzxh} </if>",
					"<if test='entity.lrr != null'>LRR = #{lrr} </if>",
					"<if test='entity.zhxgip != null'>ZHXGIP = #{zhxgip} </if>",
					"<if test='entity.zt != null'>ZT = #{zt} </if>",
					"<if test='entity.qzzt != null'>QZZT = #{qzzt} </if>",
					"<if test='entity.gmrq != null'>GMRQ = #{gmrq} </if>",
					"<if test='entity.sccj != null'>SCCJ = #{sccj}</if>",
				"</where>",
			"</script>"
	})
	int deleteEntity(@Param("entity")QZDYEntity qZDYEntity);
	
	@Delete({
		"<script>",
		"<foreach collection ='list' item='obj' separator =';'>",
			"delete from T_DW_MQJBXX_QZCL_MX",
			"<where>",
				"<if test='obj.dwdm != null'>DWDM = #{obj.dwdm}</if>",
				"<if test='obj.xh != null'>XH = #{obj.xh}</if>",
				"<if test='obj.cxd != null'>CXD = #{obj.cxd}</if>",
				"<if test='obj.qzzl != null'>QZZL = #{obj.qzzl}</if>",
				"<if test='obj.zhxgr != null'>ZHXGR = #{obj.zhxgr}</if>",
				"<if test='obj.qh != null'>QH = #{obj.qh}</if>",
				"<if test='obj.zhxgsj != null'>ZHXGSJ = #{obj.zhxgsj}</if>",
				"<if test='obj.lrsj != null'>LRSJ = #{obj.lrsj}</if>",
				"<if test='obj.scrq != null'>SCRQ = #{obj.scrq}</if>",
				"<if test='obj.lrip != null'>LRIP = #{obj.lrip}</if>",
				"<if test='obj.qzxh != null'>QZXH = #{obj.qzxh}</if>",
				"<if test='obj.lrr != null'>LRR = #{obj.lrr}</if>",
				"<if test='obj.zhxgip != null'>ZHXGIP = #{obj.zhxgip}</if>",
				"<if test='obj.zt != null'>ZT = #{obj.zt}</if>",
				"<if test='obj.qzzt != null'>QZZT = #{obj.qzzt}</if>",
				"<if test='obj.gmrq != null'>GMRQ = #{obj.gmrq}</if>",
				"<if test='obj.sccj != null'>SCCJ = #{obj.sccj}</if>",
			"</where>",
		"</foreach >",
		"</script>"
	})
	int batchDeleteEntity(@Param("list")List<QZDYEntity> qZDYEntitys);
}
